### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by zen0bit**

### CODE REVIEW

**Comment by cforce** [comment]
@GhomKrosmonaute  Please merge

**Review by zen0bit — COMMENTED** [review]
lgtm

**Comment by cforce** [comment]
can you elaborate which branch makes into the npm module (is it  providers?) and when its finally expected to be packaged into the npm?
I'm so lazy - I hate to write the comments myself  .. :-)

**Comment by zen0bit** [comment]
I think better to ask on origin repo...
https://github.com/di-sukharev/opencommit

**Comment by cforce** [comment]
Which pull request is the one?

**Pull request merged**
